name: on commit ci pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - development

jobs:
  go-fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Run go fmt
        run: go fmt ./...

      - name: Run go test
        run: go test -v ./...